{
 "title": "Miner Overall Status",
 "tags": [
  "Miner",
  "Overall_Status"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Useful Dashboard", "type": "dashlist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "min_Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_time - node_boot_time)"
    }
   ]
  },
  {
   "title": "GPU Core",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_gpu_metrics{content=\"GPU_PWR\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_0_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"0\"})"
    }
   ]
  },
  {
   "title": "GPU_1_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"1\"})"
    }
   ]
  },
  {
   "title": "GPU_2_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"2\"})"
    }
   ]
  },
  {
   "title": "GPU_3_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"3\"})"
    }
   ]
  },
  {
   "title": "GPU_4_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"4\"})"
    }
   ]
  },
  {
   "title": "GPU_5_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"5\"})"
    }
   ]
  },
  {
   "title": "GPU_6_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"6\"})"
    }
   ]
  },
  {
   "title": "GPU_7_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"7\"})"
    }
   ]
  },
  {
   "title": "GPU_0_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"0\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"0\"})"
    }
   ]
  },
  {
   "title": "GPU_1_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"1\"})"
    }
   ]
  },
  {
   "title": "GPU_2_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"2\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"2\"})"
    }
   ]
  },
  {
   "title": "GPU_3_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"3\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"3\"})"
    }
   ]
  },
  {
   "title": "GPU_4_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"4\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"4\"})"
    }
   ]
  },
  {
   "title": "GPU_5_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"5\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"5\"})"
    }
   ]
  },
  {
   "title": "GPU_6_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"6\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"6\"})"
    }
   ]
  },
  {
   "title": "GPU_7_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"7\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"7\"})"
    }
   ]
  },
  {
   "title": "GPU_0_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"0\"}) "
    }
   ]
  },
  {
   "title": "GPU_1_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"1\"}) "
    }
   ]
  },
  {
   "title": "GPU_2_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"2\"}) "
    }
   ]
  },
  {
   "title": "GPU_3_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"3\"})"
    }
   ]
  },
  {
   "title": "GPU_4_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"4\"}) "
    }
   ]
  },
  {
   "title": "GPU_5_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"5\"}) "
    }
   ]
  },
  {
   "title": "GPU_6_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"6\"}) "
    }
   ]
  },
  {
   "title": "GPU_7_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"7\"}) "
    }
   ]
  },
  {
   "title": "GPU_FAN_CHART",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  },
  {
   "title": "GPU_MEM_CHART",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_MEM\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  },
  {
   "title": "GPU_PWR_CHART",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  }
 ]
}