{
 "title": "Miner 1",
 "tags": [ "Miner" ],
 "time": { "to": "now", "from": "now-12h" },
 "panels": [
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "y": 0, "h": 5, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", monitor=\"CENTRAL MONITOR\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "min_Uptime",
   "type": "singlestat",
   "gridPos": { "y": 5, "h": 4, "w": 4, "x": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_time{instance!=\"localhost:9100\"} - node_boot_time{instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU Core",
   "type": "singlestat",
   "gridPos": { "y": 5, "h": 4, "w": 20, "x": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_gpu_metrics{content=\"GPU_PWR\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_0_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"0\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_1_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"1\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_2_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"2\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_3_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"3\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_4_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"4\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_5_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"5\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_6_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"6\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_7_FAN",
   "type": "singlestat",
   "gridPos": { "y": 9, "h": 4, "w": 3, "x": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"7\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_0_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"0\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"0\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_1_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"1\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"1\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_2_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"2\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"2\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_3_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 9 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"3\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"3\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_4_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"4\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"4\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_5_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 15 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"5\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"5\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_6_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 18 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"6\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"6\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_7_MEM",
   "type": "singlestat",
   "gridPos": { "y": 13, "h": 4, "w": 3, "x": 21 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"7\", instance!=\"localhost:9100\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"7\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_0_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"0\", instance!=\"localhost:9100\"}) "
    }
   ]
  },
  {
   "title": "GPU_1_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 3 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"1\", instance!=\"localhost:9100\"}) "
    }
   ]
  },
  {
   "title": "GPU_2_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 6 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"2\", instance!=\"localhost:9100\"}) "
    }
   ]
  },
  {
   "title": "GPU_3_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 9 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"3\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "GPU_4_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 12 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"4\", instance!=\"localhost:9100\"}) "
    }
   ]
  },
  {
   "title": "GPU_5_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 15 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"5\", instance!=\"localhost:9100\"}) "
    }
   ]
  },
  {
   "title": "GPU_6_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 18 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"6\", instance!=\"localhost:9100\"}) "
    }
   ]
  },
  {
   "title": "GPU_7_PWR",
   "type": "singlestat",
   "gridPos": { "y": 17, "h": 4, "w": 3, "x": 21 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"7\", instance!=\"localhost:9100\"}) "
    }
   ]
  },
  {
   "title": "GPU_FAN_CHART",
   "type": "graph",
   "gridPos": { "y": 21, "h": 8, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\", instance!=\"localhost:9100\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  },
  {
   "title": "GPU_MEM_CHART",
   "type": "graph",
   "gridPos": { "y": 29, "h": 8, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_MEM\", instance!=\"localhost:9100\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  },
  {
   "title": "GPU_PWR_CHART",
   "type": "graph",
   "gridPos": { "y": 37, "h": 8, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\", instance!=\"localhost:9100\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  }
 ]
}