{
 "title": "Miner Overall Status",
 "tags": [
  "Miner",
  "Overall_Status"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", monitor=\"CENTRAL MONITOR\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "min_Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_time{instance=\"miner1\"} - node_boot_time{instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU Core",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_gpu_metrics{content=\"GPU_PWR\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_0_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"0\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_1_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"1\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_2_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"2\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_3_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"3\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_4_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"4\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_5_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"5\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_6_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"6\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_7_FAN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\",devid=\"7\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_0_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"0\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"0\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_1_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"1\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"1\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_2_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"2\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"2\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_3_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"3\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"3\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_4_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"4\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"4\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_5_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"5\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"5\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_6_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"6\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"6\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_7_MEM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_MEM\",devid=\"7\", instance=\"miner1\"}) / sum(node_gpu_metrics{content=\"GPU_MAX_MEM\",devid=\"7\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_0_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"0\", instance=\"miner1\"}) "
    }
   ]
  },
  {
   "title": "GPU_1_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"1\", instance=\"miner1\"}) "
    }
   ]
  },
  {
   "title": "GPU_2_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"2\", instance=\"miner1\"}) "
    }
   ]
  },
  {
   "title": "GPU_3_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"3\", instance=\"miner1\"})"
    }
   ]
  },
  {
   "title": "GPU_4_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"4\", instance=\"miner1\"}) "
    }
   ]
  },
  {
   "title": "GPU_5_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"5\", instance=\"miner1\"}) "
    }
   ]
  },
  {
   "title": "GPU_6_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"6\", instance=\"miner1\"}) "
    }
   ]
  },
  {
   "title": "GPU_7_PWR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\",devid=\"7\", instance=\"miner1\"}) "
    }
   ]
  },
  {
   "title": "GPU_FAN_CHART",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_FAN\", instance=\"miner1\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  },
  {
   "title": "GPU_MEM_CHART",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_MEM\", instance=\"miner1\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  },
  {
   "title": "GPU_PWR_CHART",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg(node_gpu_metrics{content=\"GPU_PWR\", instance=\"miner1\"}) by (devid)",
     "legendFormat": "Device-{{devid}}"
    }
   ]
  }
 ]
}