{
 "title": "Page One",
 "tags": [ "Overaall Status" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total G-Card",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_gpu_metrics{content=\"GPU_PWR\", instance!=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "Number of Losed Miner",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{instance!=\"localhost:9100\"} == 0)"
    }
   ]
  },
  {
   "title": "Instance Down",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=\"InstanceDown\",alertstate=\"firing\",monitor=\"CENTRAL MONITOR\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lose G-Card",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=\"LoseGPU\",alertstate=\"firing\",monitor=\"CENTRAL MONITOR\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall View",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(node_gpu_metrics{content=\"GPU_STATUS\", instance!=\"localhost:9100\"}) by (instance,devid)"
    }
   ]
  }
 ]
}